name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-all:
    name: Build All Configurations (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025-vs2026
            os_name: windows
            arch: x64
          - os: ubuntu-26.04
            os_name: linux
            arch: x86_64
          - os: macos-26
            os_name: macos
            arch: arm64
    steps:
      - uses: actions/checkout@v6
      - name: Build (using composite action)
        uses: ./.github/actions/builds
        with:
          os: ${{ matrix.os }}
          os_name: ${{ matrix.os_name }}
          arch: ${{ matrix.arch }}
          create_release: 'false'
